- id: alembic-linear-migrations
  name: alembic-linear-migrations
  description: This hook tracks the existing alembic migrations.
  entry: hooks/alembic_linear.sh
  language: script
  types: [shell]
  # stages: [pre-commit, pre-merge-commit, manual]
  pass_filenames: false