- id: alembic-linear-migrations
  name: alembic-linear-migrations
  description: This hook tracks the existing alembic migrations.
  entry: hooks/alembic_linear.sh
  language: script
  types: [shell]
  pass_filenames: false
  always_run: true