[tool.pre-commit]
repo = "https://github.com/sergio-voxy/alembic-linear-migrations"
rev = "v0.1.0"
hooks = [
    { id = "alembic-linear-migrations" }
]

[tool.pre-commit.hooks.alembic-linear-migrations]
name = "create hash from the list of existing migrations"
entry = "hooks/alembic_linear.sh"
